config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root "games#index"
  resources :games do
    member do
      post 'add_favorite'
      delete 'remove_favorite'
    end
  end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
end

app/models/game.rb
class Game < ActiveRecord::Base
  default_scope {order('created_at DESC')}
  belongs_to :user
  has_many :favorites
  has_many :users, through: :favorites

  def Game.search(search)
    where("category LIKE ?", "%#{search}%")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :games
  has_many :favorites
  has_many :games, through: :favorites, source: :game

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :add_favorite, :remove_favorite]

  def index
      # does the same thing as set_game in the before_action
    # if current_user
    #   @games = current_user.games
    # else
    #   @games = Game.all
    # end
    if params[:category]
      @games = Game.search(params[:category]).paginate(page: params[:games_page])
    else
      @games = Game.all.paginate(page: params[:games_page])
    end
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def create
      # does the same thing as set_game in the before_action
    # @game = current_user.games.create(game_params)
    @game = Game.create(game_params.merge(user: current_user))
    redirect_to @game
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    @game.update(game_params.merge(user: current_user))
    redirect_to @game
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to games_path
  end

  def add_favorite
    @game = Game.find(params[:id])
    @game.favorites.create(user: current_user)
    redirect_to game_path(@game)
  end

  def remove_favorite
    @game = Game.find(params[:id])
    @game.favorites.where(user: current_user).destroy_all
    redirect_to game_path(@game)
  end

  private
    def game_params
      params.require(:game).permit(:name, :category, :equipment, :num_players, :num_teams, :game_duration, :description, :image_url)
    end

    def set_game
      @game = Game.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_form.html.erb
<%= form_for @game do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :category %>
  <%= f.select :category, [ ["Active", "Active"], ["Cards", "Cards"], ["Party", "Party"], ["Car", "Car"], ["Play-along", "Play-along"] ] %>
  <%= f.label :equipment %>
  <%= f.text_field :equipment %>
  <%= f.label :number_of_players %>
  <%= f.text_field :num_players %>
  <%= f.label :number_of_teams %>
  <%= f.text_field :num_teams %>
  <%= f.label :game_duration %>
  <%= f.text_field :game_duration %> minutes
  <%= f.label :image_url %>
  <%= f.text_field :image_url %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit %>
<% end %>

app/views/games/edit.html.erb
<%= render "form" %>

app/views/games/index.html.erb
<%= form_tag games_path, :method => 'get' do %>
  <p>
    <%= select_tag :category, options_for_select(["Active", "Cards", "Party", "Car", "Play-along"]), :class => "btn btn-default dropdown-toggle btn-lg" %>
    <%= submit_tag "Search by category", :name => nil, :class => 'btn btn-default btn-sm' %>
  </p>
<% end %>

<%= link_to "Create a game", new_game_path, :class => "btn btn-success btn-md" %>



  <% @games.each do |game| %>

  <div class="container">
      <div class="panel panel-default">
        <div class="panel-heading"><%= link_to game.name, game %></div>
        <div class="panel-body">
          <p><%= "#{game.category}" %></p>
        </div>
        <ul class="list-group">
          <li class="list-group-item"><%= image_tag "#{game.image_url}", class: "img" %></li>

        </ul>
      </div>
    </div>

  <% end %>

app/views/games/new.html.erb
<%= render "form" %>

app/views/games/show.html.erb
<h2><%= @game.name %>

  <% if Favorite.find_by(user: current_user, game: @game) %>
    <%= link_to "&#9733".html_safe, remove_favorite_game_path(@game), method: :delete, class: "fav" %>
    <% else %>
      <%= link_to "&#9734".html_safe, add_favorite_game_path(@game), method: :post, class: "no-fav" %>
    <% end %>
</h2>
  <br>
  <strong>Category: </strong><%= @game.category %>
  <br>
  <strong>Equipment: </strong><%= @game.equipment %>
  <br>
  <strong>Number of Players: </strong><%= @game.num_players %>
  <br>
  <strong>Number of Teams: </strong><%= @game.num_teams %>
  <br>
  <strong>Duration: </strong><%= @game.game_duration %> minutes
  <br>

  <%= image_tag @game.image_url, :class => "show_image" %>
  <br>
  <br>
  <strong>Description: </strong><%= @game.description %>
  <br>
  <br>

  <% if current_user == @game.user %>
    <%= link_to "", edit_game_path(@game), :class => "glyphicon glyphicon-pencil btn btn-warning btn-sm" %>
  <% end %>

  <% if current_user == @game.user %>
    <%= link_to "", @game, method: :delete, :class => 'glyphicon glyphicon-remove btn btn-danger btn-sm' %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name = "viewport" content = "width = device-width, initial-scale = 1">
  <title>Culdesac</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha256-KXn5puMvxCw+dAYznun+drMdG1IFl3agK0p/pqT9KAo= sha512-2e8qq0ETcfWRI4HJBzQiA3UoyFk6tbNyG+qSaIBZLyW9Xf3sWZHN/lxe9fTh1U45DpPf07yj94KsUHHWe4Yk1A==" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

</head>
<body>
  <!-- data-spy="affix" data-offset-top="0" -->
      <header>
        <h1 class="navbar-culdesac" data-toggle="tooltop" data-placement="bottom" title="Home Button"><%= link_to "Culdesac", root_path %></h1>

        <% if current_user %>
          Welcome, <%= current_user.email %>
          <h3><%= link_to 'Signout', destroy_user_session_path, :method => :delete %></h3>
        <% else %>
          <h3><%= link_to 'Signup', new_user_registration_path %></h3>
          <h3><%= link_to 'Login', new_user_session_path %></h3>
        <% end %>
      </header>

<%= yield %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
</body>
</html>